### ISSUE TITLE
Small number of post review comments

### ISSUE THREAD

**Issue by kbarnhart** [szwiep/py_SBeLT#22]
@szwiep and @smchartrand 

Two small comments from me before I ask the reviewers to finalize their reviews. 

1. In the paper and the readme, I'd recommend defining the acronym pySBeLT. Stochastic BedLoad Transport? Something else?
2. There are a few citations that are misformatted (lines 12, 15, and 29,  Wainwright:2014, Wu:2019; LeeJerol:2018)

https://github.com/openjournals/joss-reviews/issues/4282

**Comment by smchartrand** [comment]
Thanks @kbarnhart 
Working on it now.

**Comment by smchartrand** [comment]
@kbarnhart - thanks for catching these. I have addressed the issues. Apologies and have a nice weekend.
